#!/bin/bash

# Local development script for running Streamlit app with authentication
# ⚠️  TEST CREDENTIALS ONLY - NOT FOR PRODUCTION
# Password: testpass123
#
# For production use, copy this file to run_local.sh.production and update
# the AUTH_PASSWORD_HASH with a secure password hash generated by hash_password.py

export AUTH_USERNAME="admin"
export AUTH_NAME="Admin User"
export AUTH_PASSWORD_HASH='$2b$12$lr5mZMaSKCaC6GbnhgHEceIciI8kPGrnHjtkpJ939hs2E1ZQh18z6'

echo "Starting Streamlit app with test credentials..."
echo "Username: admin"
echo "Password: testpass123"
echo ""

uv run streamlit run app.py
